"""modified tables content

Revision ID: 1ecf5a8e8798
Revises: 53eedc0cd75c
Create Date: 2024-03-12 08:36:32.797391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ecf5a8e8798'
down_revision = '53eedc0cd75c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.DATETIME(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_column('deadline')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.TIME(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('deadline',
               existing_type=sa.DateTime(),
               type_=sa.TIME(),
               existing_nullable=True)

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deadline', sa.TIME(), nullable=True))

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('date',
               existing_type=sa.String(),
               type_=sa.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
