"""Add organizer_id

Revision ID: 53eedc0cd75c
Revises: a91465862789
Create Date: 2024-03-08 20:43:22.652736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53eedc0cd75c'
down_revision = 'a91465862789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('rescources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('organizer_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('task_assignments', schema=None) as batch_op:
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('rescources', schema=None) as batch_op:
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_column('organizer_id')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_column('organizer_id')

    # ### end Alembic commands ###
